### ISSUE TITLE
[W3-pipelines-project] Ana G.

### ISSUE THREAD

**Issue by AnaAGG** [Ironhack-Data-Madrid-Enero-2021/W3-pipelines-project#10]
https://github.com/AnaAGG/P2_Kaggle-API.git

**Comment by olmocorell** [comment]
¡¡Hola, holaaaaa Ana !! 🚀 🚀 🚀 
Te cuento cositas del proyecto. 

### Readme
Tu readme está perfecto, realmente bien. Solo te pongo una peguita, y es por ser tiquismiquis.
<img width="432" alt="Captura de pantalla 2021-02-08 a las 17 12 45" src="https://user-images.githubusercontent.com/57899051/107246761-dfc2eb80-6a30-11eb-981b-358093555920.png">
No pongas en el texto "import pandas as pd" si no algo así:
[Pandas](https://pandas.pydata.org/) - Visualización y manipulación de dataframes
Pero vamos, por ponerme tiquismiquis y que esté de matrícula ¿valep?


### Code/Repository structure
Vale, la estructura del repo está bien pero me he dado un súper susto con los jupyter, que no los encontraba porque están en output. 
Reserva esta carpeta para cosas que tu proyecto produzca. En plan, si haces gráficos o mapas puedes exportarlos ahí, si haces una limpieza de datos y el ejecutable empieza leyendo un csv y acaba exportando otro mételo ahí... ¿vale?
Los jupyter en una carpeta de notebook si son muchos. Bueno, esto no es una norma exacta, es como yo lo haría.

### Code efficiency / Code syntax (conventions)
[Esto](https://github.com/AnaAGG/P2_Kaggle-API/blob/main/src/functions_pipeline.py) me ha encantado. Enhorabuena.
Funciones pequeñitas de propósito único y bien documentadas. Documentar las funciones es siempre una buena práctica así que ENHORABUENA.
¿Qué me ha faltado? que directamente hicieras el pipeline en un archivo en vez de en un jupyter. Es decir, que en vez de llamar a la función desde el jupyter hagas en un .py un hilo de ejecución llamando a todas las funciones que necesitas para importar un archivo, procesarlo y exportarlo una vez procesado...que es el objetivo de un pipeline. 

Por aquí:
<img width="1054" alt="Captura de pantalla 2021-02-08 a las 18 48 39" src="https://user-images.githubusercontent.com/57899051/107260301-4569a480-6a3e-11eb-93c4-4f6919b0b159.png">
Veo código atomizable. Este tronchito lo puedes hacer enterito con un bucle en el que iteras sobre una lista de "strings" y te sacas los diferentes regplot. Es más, si tienes una función que te saca el regplot y a la que le metes unos parámetros directamente haces un bucle iterando por la lista, sacas el gráfico llamando a la función y te setea el axis con ese string que utilizas para la columna... no sé si me estoy explicando muy bien, pero bueno, te lo explico cuando quieras, como siempre 😄 .


### Improvements
En general: trabajazo increíble, la verdad. Enhorabuena por todo, las llamadas a la API, las funciones, la visualización pero, sobre todo, por la increíble evolución que está sufriendo tu código. Enhorabueuna y buen trabajo. Te pongo de mejoras lo que te he dicho más arriba.
- Código que se repite, haz una función.
- No tengas miedo a hacer bucles y a llamar funciones dentro de ellos
- El pipeline en un ejecutable
- Los enlacitos del readme (es una bobada)

Esto es todo, si necesitas ver cualquier cosa ya sabes dónde estoy.
¡¡A por elloooooooooooo!! ¡¡Sigue así!!


![unnamed2](https://user-images.githubusercontent.com/57899051/107261129-39caad80-6a3f-11eb-952e-ea22222d6561.png)
