### ISSUE TITLE
[W3-pipelines-project] Alex Moreno

### ISSUE THREAD

**Issue by amorenorp** [Ironhack-Data-Madrid-Enero-2021/W3-pipelines-project#11]
https://github.com/amorenorp/Trump_tweets_Analysis_WebScrapping

**Comment by olmocorell** [comment]
¡¡Hola Hola Alex!!  🚀 💪🏻 
¡¡Vamos a ver tu proyecto de pipelines!!


### Readme
Está perfecto, enhorabuena. Has seguido todos nuestros consejos y has hecho un readme como se espera. Limpio, ordenado, que explica el proyecto y con los enlaces a la documentación. Buen trabajo. 🔝 

### Code/Repository structure
La organización del repositorio está perfecta. En el caso de los notebooks puedes hacer una carpeta a parte de notebooks y dejar en src/source solo los archivos de funciones que son los que llevan el "código fuente" propiamente dicho y 

### Code efficiency / Code syntax (conventions)
Espectacular tu main.py simplemente:
<img width="640" alt="Captura de pantalla 2021-02-08 a las 13 23 10" src="https://user-images.githubusercontent.com/57899051/107219040-cd38ba00-6a10-11eb-96e9-daee0040ca4c.png">
No hace falta que hagas una función que llame a otras funciones y luego la llames a ella, simplemente, el archivo ejecutable ya es un pipeline si llamas a una función detrás de otra y haces un hilo de ejecución. Está perfecto. Has entendido el concepto de lo que es un pipeline, de un ejecutable y de atomizar el código.
Tener todas las funciones documentadas es una buena práctica, así que enhorabuena por ello. Muy bien ese punto.

Todo esto, ya que has hecho un ejecutable de limpieza, no debería estar aquí. El tema del ejecutable era que pudieras hacer todo lo relacionado con la limpieza ahí y marcarte la visualización sobre un data que simplemente cargas porque ya lo has hecho previamente. Lo podíamos hacer en un jupyter para probar y luego una vez pasado al ejecutable, lo quitamos de aquí:
<img width="1055" alt="Captura de pantalla 2021-02-08 a las 13 33 44" src="https://user-images.githubusercontent.com/57899051/107220136-48e73680-6a12-11eb-8104-5651ef9b0beb.png">

Enhorabuena: por haberte metido en el fango con Selenium. Muy buen trabajo.

Ojo con dejar prints infinitos en los [jupyter](https://github.com/amorenorp/Trump_tweets_Analysis_WebScrapping/blob/main/source/API%20RAPID%20YAHOO.ipynb)

El archivo de visualización está genial.

### Improvements
Vale, por aquí te voy a poner poco, porque tengo que reconocer que tu proyecto está "excelente" y así lo voy a dejar reflejado en nuestro panel de control. Es un proyecto de 10, la verdad. Así que enhorabuena.
Apúntate el par de mejoras que te he comentado y, de cara a futuro, vamos a empezar con la parametrización de funciones. Intentaremos hacer funciones más generalistas que podamos reutilizar y le meteremos parámetros. De cara a futuros proyectos. 
Pero vamos, que... enhorabuena Alex, un trabajo muy meticuloso. 
Cualquier cosa que quieras revisar me dices ¿vale?

¡¡A por ello!!

![unnamed2](https://user-images.githubusercontent.com/57899051/107220985-518c3c80-6a13-11eb-99b5-56e6bd45d4ed.png)
