### ISSUE TITLE
[W3-pipelines-project] Sonia Garcia

### ISSUE THREAD

**Issue by Fominayasg** [Ironhack-Data-Madrid-Enero-2021/W3-pipelines-project#12]
https://github.com/Fominayasg/W3-pipelines-project-artic_mammals.git

**Comment by breogann** [comment]
Hola Sonia! 🙋🏻‍♂️

Te comento lo que voy viendo. 

El proyecto tenía dos objetivos: **enriquecer** datos & hacer un **pipeline:** te falta la parte del pipeline! realmente es lo mismo que tienes pero llamando a las funciones y ejecutándolos con python3. 

- Respecto a la **organización del repositorio 📚**
    - El .**gitignore**: perfect **👌.** No se te ha colado ningún archivo temporal/oculto.
    - Para el resto: también perfect. Como mucho, igual numeraría los jupyters, pero esto ya es ~~toc~~ preferencia personal.
    - Aunque tengas un jupyter para la API, has modularizado las funciones luego llevándolas a un [archivo.py](http://archivo.py) como pedíamos 🔝
- El **[README.md](http://readme.md) ✍🏻**:  No se te renderiza la imagen. La has llamado en minúscula cuando la carpeta empieza por mayúscula; prueba cambiando eso.
    - Súper por haber explicado el formato de los datos.
    - Por ponerle más miga, puedes añadir librerías que has utilizado (con sus enlaces), imágenes generadas, etc.
- El **ejecutable ⚡️**: casi lo tienessssss. Es cuestión de llamar a las funciones de limpieza (o sea definirlas como las tienes y luego llamarlas 'limpieza_columnas()'), asegurarte del input que reciben y de ejecutar al archivo.
- Respecto al **código** 👩‍💻:
    - Para los docstrings: como os ponía por slack:

        ```python
        def hacer_cosas ():
        '''Esto hace cosas.
        Takes: cosas
        Returns: otras'''
        	return cosas
        ```

        déjalo comentado como te gustaría encontrártelo. Eso para el docstring, aunque veo que lo has ido comentando con almohadillas!

    - Veo que has reutilizado funciones del proyecto anterior para tu magia 👀. Que no está mal!
    - Para api_functions.py, veo que utilizas como argumento el token, pero no lo tienes definido como variable ni importado. Entiendo que lo copiaste del jupyter, pero te faltaría incluirlo. (veo que aquí si has puesto docstrings)
    - Y las has importado al jupyter luego 🙌
    - Por la parte de código has hecho funciones sencillas que manipulan dataframes y que hacen llamadas a API y que, no cambiaría nada.
    - Por la parte de visualización, cuidado con las leyendas! Igual puedes agrupar por décadas. No me esperaba ese gráfico, pero a priori parece representar bien la información.
    - Por último, puedes exportarlas en archivos png! (y si haces el pipeline y haces limpieza + API junto, puedes incluso ejecutar python3 del tirón y hacer que se te generen y se te abran en finder 🔥)

Enhorabuena porque se ve que te lo has trabajado (aunque falta lo del ejecutable!). Sigue así y a darle duro, que los siguientes los vas a bordar!! 🚀🚀

![image](https://user-images.githubusercontent.com/54676992/106669747-664c7880-65ac-11eb-8cf9-30c7f4b23577.png)
