### ISSUE TITLE
[W3-pipelines-project] Juan José Triviño

### ISSUE THREAD

**Issue by JJTrivino** [Ironhack-Data-Madrid-Enero-2021/W3-pipelines-project#13]
https://github.com/JJTrivino/W3-project

**Comment by olmocorell** [comment]
¡¡Hola Juanjo!! 🚀 💪🏻 
Vengo por aquí pero no me voy a explayar porque te dimos feedback en el momento de todos los puntos mejorables el martes de tu presentación. 
Si te quedaste con alguna duda o quieres revisar algo en concreto cuenta conmigo sin ningún problema.
Recordarte que me gustó mucho tu proyecto y que te lanzaras con web scraping. Te recomiendo selenium si te ha gustado el proyecto para hacer un poco de scraping avanzado y bueno, para cuando tengas tiempo.
¡¡Buen trabajo!! ¡Sigue dándole duro!


![unnamed2](https://user-images.githubusercontent.com/57899051/107261336-7dbdb280-6a3f-11eb-86e8-5bd834e71423.png)
