### ISSUE TITLE
[W3-pipelines-project] Jean Charles Yamada

### ISSUE THREAD

**Issue by yamadajc** [Ironhack-Data-Madrid-Enero-2021/W3-pipelines-project#14]
https://github.com/yamadajc/Pipeline-Project-MobilityCovidMap

**Comment by breogann** [comment]
Hola ~~Ana~~ Jeancha! 🙋🏻‍♂️

Vamos a echar un ojo al proyecto, que *parece que tiene buena pinta.*

Te comento lo que voy viendo. Si ves que te comento mucho, es porque en los proyectos somos muy pesados, no es porque tengáis muchas cosas mal, sino porque es donde más se aprende y donde siempre se puede mejorar. 

De todas formas la mayor parte de las cosas te las hemos dicho en la presentación, pero te lo dejo por aquí.

El proyecto tenía dos objetivos: **enriquecer** datos & hacer un **pipeline**. 

- Para el primero: utilizar una API o web scrapping para relacionar los datos.
- Para el segundo: que  haya un pipeline quiere decir que el resultado de una función fuera la entrada de otra. Es decir, que ejecutando una acción, los datos se procesen de varias formas para devolver un output diferente al inicial. Aquí, como te decía, puedes hacer un ejecutable para que el dataset que tienes descargado en local salga exportado. Entra: la ruta relativa del csv; devuelve: un archivo.csv limpio.
- Respecto a la **organización del repositorio 📚**
    - El .gitignore:
        - ¿Dónde está? queyolovea. En este caso no tienes archivos ocultos/temporales, no sé si porque los borraste o porque no se te han generado.
        - La distribución de carpetas/archivos está perfecta.
- El **[README.md](http://readme.md) ✍🏻**:  Súper bien explicado el readme. Le metería más miga:
    - Tu objetivo no es manipular datos, tu objetivo es llegar a una conclusión y manipular los datos es el medio. Plantea tu Ho.
    - Utiliza los gráficos que has exportado en el readme. También las conclusiones. (si quieres dejarlas, o si quieres invitar al lector a que entre a los jupyters, como decía Ras )
- El ejecutable:

    ![image](https://user-images.githubusercontent.com/54676992/106586459-c578a180-6548-11eb-9dea-64cb704420ba.png)

    Una vez tienes las funciones y el repo hecho, es súper fácil hacerlo: para la función de descargar, te vale con crear una función que reciba la ruta relativa y abra el dataframe. Luego pasas el resto de funciones en base a ese dataframe. Y con eso puedes hacer un 

    ```python
    python3 jeanchaejecutable.py
    ```

    que se llamará de otra forma.

- Respecto al código 👩‍💻:
    - Genial por exportar las gráficasss
    - En general muy buen manejo de pandas 👏
    - Gracias por haber ido comentando con títulos el proceso que vas haciendo e ir concluyendo.
    - Como te decía, busca la forma de poder relacionar los datos. Si puedes hacer ese mismo análisis sin haber utilizado el scrapping, es que algo está fallando: son datos que no te añaden valor.
    - Por la parte de la visualización, están súper las series temporales. Como te decíamos, cambia las etiquetas, si puedes quita el ruido de fondo y asegúrate de marcar eventos significativos para tu análisis, como el comienzo del confinamiento.
    - Cuando crees las funciones, asegúrate de poner un buen docstring.

        ```python
        #El docstring:
        def hacer_cosas():
        '''Esta función hace cosas.
        Takes: cosas
        Returns: otras'''
        return otrascosas
        ```

Ya te digo que te comentamos muchas cosas porque vamos a buscar el fallo, que queremos que lo dejéis perfect. 

Está genial el proyecto Jeancha! Has limpiado dataframes y has hecho web scrapping 👏 Puedes mejorarlo, los puntos clave que te faltan son:

1. Que lleves las funciones a tu archivo de funciones
2. Que scrappes/utilices los datos utilizados de forma relacionada
3. Que puedas hacer el ejecutable

Sigue así y a darle duro!! 🚀🚀 ya nos corregirás tú la estadstica la semana que viene 💪

![image](https://user-images.githubusercontent.com/54676992/106589384-41281d80-654c-11eb-9a16-4aaef57105f4.png)
