### ISSUE TITLE
[ W3-pipelines-project] Floren Gutiérrez

### ISSUE THREAD

**Issue by florengutierrez** [Ironhack-Data-Madrid-Enero-2021/W3-pipelines-project#15]
https://github.com/florengutierrez/Pipelines-project

**Comment by breogann** [comment]
Hola Floren! 🙋🏻‍♂️

Te comento: somos muy pesados, pero tener los proyectos bien hechos es muy importante, así que te voy a dar todo el feedback que pueda. 

El proyecto tenía dos objetivos: **enriquecer** datos & hacer un **pipeline**. 

- Para el primero: utilizar una API o web scrapping para relacionar los datos.
- Para el segundo: que haya un pipeline quiere decir que el resultado de una función fuera la entrada de otra. Es decir, que ejecutando una acción, los datos se procesen de varias formas para devolver un output diferente al inicial. Aquí puedes hacer un ejecutable donde el resultado de la primera función (la descarga del dataset) sea la entrada de la(s) segunda(s) funcion(es) de limpieza. El flujo de ejecución sería:

    url > df_descargado > df_limpio 

- Respecto a la **organización del repositorio 📚**
    - El gitignore: Está perfect. No se te ha colado ningún archivo oculto/temporal. Puedes echar un ojo al gitignore que tenemos en los labs, ahí están los mismos archivos que tienes ignorados, pero de forma recursiva, de forma que no tienes que poner la ruta entera, sino que te los ignora de forma recursiva.
    - Numera los notebooks según el orden lógico 🙏 1-limpieza, 2-api, 3-merge, 4-visualización,...etc.
    - En la carpeta de src está el código como tal, que luego importas en los jupyters para el flujo de trabajo. Puedes separarlos y dejar sólo archivos de funciones en src y los notebooks aparte.
- El **[README.md](http://readme.md) ✍🏻**:  Súper bien explicado el readme. Lo único que quizá le podría añadir son lso gráficos que sacas en el jupyter.
- El ejecutable ⚡️: tienes el archivo de funciones pero sólo te falta llamarlas. Una vez las llames y exportes el csv, estaría listo! Eso sí, no lo llames como [funciones.py](http://funciones.py), llámalo según el contenido.
- Respecto al código 👩‍💻:
    - Importas algunas funciones al jupyter desde el archivo de funciones y luego tienes otras definidas dentro del notebook. Puedes hacer lo mismo. Aunque no sean parte del ejecutable, esas funciones que crees también las puedes atomizar (hacer que cumplan objetivos pequeños) y modularizarlas (encapsular en código en funciones que reciben o no argumentos) y guardarlas en un archivo de python diferente. Para el proyecto de geoqueries, hará falta que hagas el mismo proceso de definición e importación.
    - Entiendo que lo que has hecho es: coger el dataset + hacer scrapping de wikipedia; y la API para las portadas al final no la acabas utilizando. Eso lo puedes meter en una función y pasar un apply para crear una nueva columna.
    - Para la visualización, puedes incluir un gráfico que enseñe la correlación entre las dos variables, que al final es tu hipótesis!
    - Para las funciones, asegúrate de poner un buen docstring.

        ```python
        #El docstring:
        def hacer_cosas():
        '''Esta función hace cosas.
        Takes: cosas
        Returns: otras'''
        return otrascosas
        ```

Está bien el proyecto Floren! Has limpiado dataframes y has hecho web scrapping (y hecho llamadas a una API)👏 Le puedes meter más miga: 

1. Hacer el ejecutable
2. Hacer más visualización
3. Modularizar las funciones de la API

Sigue así y a darle duro!! 🚀🚀

![image](https://user-images.githubusercontent.com/54676992/107179709-7fec2680-69d7-11eb-9e5a-ebbfbcd0159d.png)
