### ISSUE TITLE
[Pipelines-project] Sergio Calero

### ISSUE THREAD

**Issue by SergioCaler0** [Ironhack-Data-Madrid-Enero-2021/W3-pipelines-project#16]
https://github.com/SergioCaler0/Pipelines-proyect

**Comment by olmocorell** [comment]
¡¡Hola Hola Sergioooooooooooo!! 🚀 💪🏻  
Vengo a comentarte cositas del proyecto de pipelines, voy a ello ¿vale?

### Readme
Vale, coleguita.... ¿qué ha pasado aquí?
<img width="677" alt="Captura de pantalla 2021-02-08 a las 19 06 03" src="https://user-images.githubusercontent.com/57899051/107262326-b316d000-6a40-11eb-8a9a-99d8920b4a04.png">
Esto es un invalid como una catedral.... tienes dos readme. El README.md que es el que lee github está vacío.
Y luego tienes otro readme que lo has abierto en jupyter (maaaaaaaaaaaal) y que está en formato jupyter... a ver, yo lo puedo abrir, y lo veo [aquí](https://github.com/SergioCaler0/Pipelines-proyect/blob/main/README.md.ipynb) pero... ¿Te das cuenta que es un archivo don dos extensiones? y ... además, github no lo lee. 
Necesitas:
1- borrar ese archivo
2- pasar esa info al README.md
3- nunca abras el readme desde jupyter, ábrelo desde el visual studio code ¿vale?

🔥 🔥 🔥 
¡a fuego con esto!


### Code/Repository structure
Vale, en la estructura del repo hay varias cosas regu... para que tomes nota ¿vale?  (tendemos a la excelencia)
Aquí:
<img width="586" alt="Captura de pantalla 2021-02-08 a las 19 09 24" src="https://user-images.githubusercontent.com/57899051/107262710-2ae4fa80-6a41-11eb-8af6-39fcbda44b5d.png">
Es una carpeta de notebooks, en la que solamente espero encontrar jupyter notebooks...se te ha colado un travieso functions.py. Échale un ojo a esto, pero te digo varias cosas:
- Nunca llamamos al archivo funciones.py, en inglés tampoco vale, ni "funcioncitas.py" ni "lasfuncionesdecalero.py" si no que intentamos poner nombres descriptivos a los archivos (igual que a las variables, siempre nombres descriptivos).
- Revisa el .gitignore, hay archivos que no hace falta subir a github, me refiero a estos:
<img width="540" alt="Captura de pantalla 2021-02-08 a las 19 28 24" src="https://user-images.githubusercontent.com/57899051/107264873-d2632c80-6a43-11eb-8ab3-1a0f886e18fd.png">


### Code efficiency / Code syntax (conventions)

Por aquí... ojo con el print infinito que te has marcado [aquí](https://github.com/SergioCaler0/Pipelines-proyect/blob/main/notebooks/Scraping%20de%20web.ipynb)

Y encima después del print infinito... ¡¡error!! revisa esto porfi...
<img width="850" alt="Captura de pantalla 2021-02-08 a las 19 53 33" src="https://user-images.githubusercontent.com/57899051/107267551-566ae380-6a47-11eb-9647-986b353bdf2c.png">

Aunque al final haces un bonito dataframe con toda la info que has sacado del web scraping, puedes hacer un poco de error handling para solucionar el tema de si la lista está fuera de rango.
El jupyter de visualización está bastante bien también. ¡¡Enhorabuena!!
Por aquí...
<img width="865" alt="Captura de pantalla 2021-02-08 a las 19 58 42" src="https://user-images.githubusercontent.com/57899051/107268154-0dfff580-6a48-11eb-83ae-1c7f6a22e1bc.png">
¡Hay código que se repite y que puede ir en funciones!

### Improvements

Recapitulo en este apartado algunas de las cositas que te he dicho...
Has hecho muy buen trabajo con el scraping, la unión de los datasets y la visualización pero.
- README revisa eso PLS
- Ejecutable .py que haga el pipeline de limpieza
- Organización del repo
- Atomización del código que repetimos en funciones.
- Archivo de funciones que no se llame functions.py pls

Y creo que esto es más o menos todo.
Podemos ver el proyecto cuando quieras y si necesitas que te explique algo en concreto o ver algo conmigo ya sabes donde estoy. ¡Siempre disponible!
Dale duro Sergio ¡¡vengaaaaaaaaaaa!! ¡¡a tope!! 🚀 🚀 🔥 🔥 💪🏻 💪🏻 


![unnamed2](https://user-images.githubusercontent.com/57899051/107268416-62a37080-6a48-11eb-9d21-a330909a0ad2.png)
