### ISSUE TITLE
[pipelines-project] Santiago Hartmann

### ISSUE THREAD

**Issue by santhart97** [Ironhack-Data-Madrid-Enero-2021/W3-pipelines-project#17]

**Comment by olmocorell** [comment]
¡Hola Santiago! 🚀 💪🏻 
Ha llegado el momento de corregir tu proyecto pero no veo enlace ni encuentro el repositorio. ¿Pudiste hacer algo al final? 
Escríbeme por slack para que concretemos cuándo puedes recuperar este trabajo y el modo de hacerlo ¿vale?. 
Tenemos un plan, pero tengo que hablarlo contigo.
¡¡Dime algo porfi!!
