### ISSUE TITLE
[demographics_pipeline] Cristina Callejo

### ISSUE THREAD

**Issue by CristinaCallejo** [Ironhack-Data-Madrid-Enero-2021/W3-pipelines-project#18]
https://github.com/CristinaCallejo/demographics_pipeline

**Comment by breogann** [comment]
Cris, lo has borrado o hecho privado? 😶

**Comment by breogann** [comment]
Hola Criiis! 🙋🏻‍♂️

¿Qué ha pasado con este proyecto? El repositorio está un poco caótico. Tienes un millón de csv's en la carpeta de data, los jupyters están con errores, no tienes readme y no tienes archivos de código en src...si se te atravesaron los diccionarios, podrías tirar también por scrapping. Pero al margen del enriquecimiento la limpieza tampoco la tienes; está todo con errores impresos de código.

Si ves que no puedes plantear el proyecto o que vas muy mal o te atascas mucho con una cosa en concreto, braséanos por slack o pide ayuda a las compañeras, pero no te quedes atascada de esta forma 😔 Si has hecho alguna modificación y no estoy viendo la última actualización, dímelo. Dinos también cómo vas con el de geoqueries. 

Ánimo Cris, que tienes el nivel y puedes sacar esto perfectamente!! 💪
