### ISSUE TITLE
[W3-pipelines-project] Ángela Navarro

### ISSUE THREAD

**Issue by angelanavarrog** [Ironhack-Data-Madrid-Enero-2021/W3-pipelines-project#2]

**Comment by angelanavarrog** [comment]
https://github.com/angelanavarrog/W3-pipelines-project

**Comment by breogann** [comment]
Hola Ángelaa! 🙋🏻‍♂️

Te comento: somos muy pesados, pero tener los proyectos bien hechos es muy importante, así que te voy a dar todo el feedback que pueda. 

El proyecto tenía dos objetivos: **enriquecer** datos & hacer un **pipeline**. 

- Para el primero: utilizar una API o web scrapping para relacionar los datos, como has hecho.
- Para el segundo: que  haya un pipeline quiere decir que el resultado de una función fuera la entrada de otra. Es decir, que ejecutando una acción, los datos se procesen de varias formas para devolver un output diferente al inicial. Aquí puedes hacer un ejecutable donde el resultado de la primera función (la descarga del dataset) sea la entrada de la(s) segunda(s) funcion(es) de limpieza. El flujo de ejecución sería:

    ruta  > df_descargado > df_limpio 

    Has hecho tu proyecto en el fork de nuestro repo. La idea es que hagáis este proyecto como uno propio y que seáis autoras de vuestro código (que aunque esté forkeado lo seguís siendo), pero que creéis el proyecto de cero como propio.

- Respecto a la **organización del repositorio 📚**
    - El .gitignore:
        - Perfect. No se te ha colado ningún archivo temporal/oculto y también el el csv!
        - Los notebooks quizá los pondría todos juntos: mergearía la carpta de Analysis y de Other relevant fils. Si los de relevant files no aportan y los has utilizado como borrador, puedes quitarlos del repo. Además, puedes numerarlos en el título porque tienen un orden lógico: 1. limpieza, 2. scrapping, 3. análisis. Así quien entre a leerlo se puede centrar en el código.
- El **[README.md](http://readme.md) ✍🏻**:  Súper bien explicado el readme. Conciso pero con los puntos que necesitas.
    - Súper bien el uso de markdown para los títulos y para los enlaces, tanto los externos como los internos.
- El ejecutable ⚡️: has puesto el códido en el cleaning.py, peero no estás exportando el dataframe. No es cuestión de copiar y pegar el código (que un poco sí), pero tienes que meterlo en funciones y luego llamarlas, para que lo que se ejecute sean funciones y no tanto líneas de código. Asegúrate de al final exportarlo también.
- Respecto al código 👩‍💻:
    - Lo mismo para el cleaning que el de scrapping fucntions. El código de esos archivos no es sólo la copia de los jupyters, sino que:
        - Tiene que estar metido en funciones
        - Las funciones tienen que tener docstring ('''Esta función hace cosas, Takes, Returns, etc''').
        - Las funciones tienen que estar atomizadas y cumplir objetivos únicos en la medida en la que se pueda.
        - Luego, si quieres que sea ejecutable, es cuestión de sólo llamarlas para que se ejecuten después de estar definidas.
        - Esta función:

            ```python
            def neighbourhood (neighbourhood_group):
                if neighbourhood_group == "Brooklyn":
                    return "Brooklyn" 
                elif neighbourhood_group == "Manhattan":
                    return "Manhattan" 
                elif neighbourhood_group == "Bronx":
                    return "Bronx"
                elif neighbourhood_group == "Queens":
                    return "Queens" 
                elif neighbourhood_group == "Staten Island":
                    return "Staten Island" 
                else:
                    return "other" 

            # Application of defined conditions in our dataframe.

            airbnb_NYC ["neighbourhood_group"] = airbnb_NYC["neighbourhood_group"].apply(neighbourhood)
            ```

            la creas para aplicarla dentro de la misma columna donde si se cumple la condición, lo igualas a lo que ya estaba antes 👀, no entiendo del todo el objetivo, ¿es por el other? porque si es así, lo puedes refactorizar. Por ejemplo, con una lista o un diccionario. Pero bienn porque has hecho apply (sabías dónde ganarnos).

        - Súper la comprehension list!

            ```python
            population2.append([cell.text for cell in row.find_all()])
            ```

        - Estos nan:

            ```python
            bronx = population_final.loc[0:10].replace(np.nan,"Bronx")
            ```

            los has reemplazado en base a alguna otra columna, entiendo. Probablemente puedas hacerlo con una función donde no tengas que utilizar el loc. 

        - En general tienes súper buen manejo de pandas.
        - La visualización y el story-telling está genial. Además, súper bien que lo hayas comentado y puesto las conclusiones.

    Ya te digo que te comentamos muchas cosas porque vamos a buscar el fallo, que queremos que lo dejéis perfect. 

Está genial el proyecto Ángela! Has limpiado dataframes y has hecho web scrapping 👏 Puedes mejorarlo, los puntos clave que te faltan son:

1. Que lleves las funciones a tu archivo de funciones (modularizadas)
2. Que puedas hacer el ejecutable

Sigue así y a darle duro!! 🚀🚀  Ya verás cómo vas a hacer proyectazos 💪

![image](https://user-images.githubusercontent.com/54676992/107035179-104c2080-67b8-11eb-819a-1ae73600e9bf.png)
