### ISSUE TITLE
[W3-pipelines-project] Antonio García

### ISSUE THREAD

**Issue by antoniogarciagiron** [Ironhack-Data-Madrid-Enero-2021/W3-pipelines-project#3]
Hola! 
Os dejo el link de mi repo, he encontrado en Kaggle una tabla con las estadísticas de las cartas/personajes de un popular juego de móvil que se llama Clash Royale. Mi intención es juntarla con datos de los sets de cartas más utilizadas en torneos (Por web scrapping) y analizar qué tienen en común las cartas más populares, con los ratios de victorias, daño por segundo, lo que cuesta invocar cada carta, etc. Espero que mole!

https://github.com/antoniogarciagiron/Pipelines-Project-Clash-Royale.git

**Comment by breogann** [comment]
Hola Toni! 🙋🏻‍♂️

Te comento lo que voy viendo. Si ves que te comento mucho, es porque en los proyectos somos muy pesados, no es porque tengáis muchas cosas mal, sino porque es donde más se aprende y donde siempre se puede mejorar. 

El proyecto tenía dos objetivos: **enriquecer** datos & hacer un **pipeline:** y has cumplido con los dos.

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: perfect **👌**
    - Para el resto: en el output sólo pondría los csv procesados. Los [archivos.py](http://archivos.py) en el src y los jupyter como quieras, o bien dentro del src o en una carpeta de notebooks.
    - Gracias por haberlos numerado 🙌
- El **[README.md](http://readme.md) ✍🏻**:  Está súuper bien, nada que decirte.
- El **ejecutable ⚡️**: lo único que te podría decir es que puedes enlazar los dos archivos de tal forma que uno llame al anterior. Así ejecutas sólo uno. También que puedes tener funciones definidas en varios archivos, no es necesario que todas estén en el mismo archivo y que las importes en los siguientes. De hecho, lo que se suele hacer es tener un solo `[main.py](http://main.py)` /app.py a nivel de root que lo que hace es coger las funciones de otros src/archivos.py. Aquí lo que has hecho es hacer todos "main" que cogen el código de un mismo archivo; que es el que tienes en src. Te dejo documentación sobre cómo es:

    [https://docs.python.org/3/library/__main__.html](https://docs.python.org/3/library/__main__.html) . No te lo pongo tanto como corrección de algo que está mal (que para ser el segundo proyecto está perfecto) sino a modo de input para que investigues sobre ello. 

- Respecto al **código** 👩‍💻:
    - A la hora de exportar los csv, los returneas sólo con el nombre. Asegúrate de poner también la extensión. Es cierto que estás utilizando el método pd.to_csv para exportar y que las extensiones son convenciones; pero te diría que mejor lo pongas: para que se sepa qué tipo de archivo es, para que (si no lo abres con python) se te abra con un programa por defecto, etc.
    - Los docstring están genial Toni. Siempre digo lo mismo, pero documentad el código como os gustaría encontrarlo.  Los jupyter también, guiados con comentarios y con conclusiones.
    - También has hecho un montón de enriquecimiento con el scrapping.
    - Los jupyter que tienes en la carpeta de otros, si no añaden información, puedes quitarlos.
    - Por último, igual que tienes el pipeline del primer csv, puedes hacer pipeline con todo y que al ejecutar todo, entre el csv y salgan las gráficas exportadas con el csv enriquecido. ¿necesario? no. ¿que puedes hacerlo de sobrísima? sí. Esto sería un extra.

Enhorabuena porque el proyecto está súuper currado y has llegado a todo lo que se te pedía y más. La verdad que muy 🔝, está de 10.

Sigue así y a darle duro!! 🚀🚀
