### ISSUE TITLE
[Proyecto W3 pipelines] Ana de Luna 

### ISSUE THREAD

**Issue by AnadeLuna** [Ironhack-Data-Madrid-Enero-2021/W3-pipelines-project#4]
https://github.com/AnadeLuna/Proyecto_WebSraping

**Comment by olmocorell** [comment]
¡¡Hola, hola Anaaaaaaaaaaa 🚀 💪🏻  !! 
¡¡Te cuento cositas del proyecto!! 

### Readme
¡Bien! Está bien, tienes bastantes cosas, pero podemos hacerle algunas mejoras...sería, ponerle un par de títulos con markdown antes del texto que está separado por las líneas. Tipo como pongo yo los títulos aquí (readme, code structure...tal)
Y luego, abajo del todo, añadimos el stack de tecnologías con algunos enlaces a la documentación en plan:
[Pandas](https://pandas.pydata.org/) - Visualización y manipulación de dataframes
y así... ¿vale?


### Code/Repository structure
Aquí:
<img width="608" alt="Captura de pantalla 2021-02-08 a las 22 26 04" src="https://user-images.githubusercontent.com/57899051/107283392-a56f4380-6a5c-11eb-82dc-d2397634402d.png">
¡quetehasliao! me refiero, que en el archivo .gitignore te falta una r y claro, .gitignoe, así no te pilla ni los ds store ni los checkpoints ni nadaaaaa.
Luego, reorganicemos esta carpeta un poquitititito:
<img width="696" alt="Captura de pantalla 2021-02-08 a las 22 32 53" src="https://user-images.githubusercontent.com/57899051/107284138-989f1f80-6a5d-11eb-8335-330a3201bab9.png">
Lo que sea jupyter notebook que nos haya servido para hacer pruebas de funciones ... o si tenemos muchos jupyter en general, los mandamos todos a una carpeta de notebooks ¿vale?.
Dejamos src o source code para archivos .py con funciones que necesitamos en otros archivos o jupyter y ya está ¿vale?
Y luego, si tenemos un data_merge lo metemos en la carpeta output. 
La carpeta output la utilizamos para meter todo lo que nuestro proyecto genera...esto es: gráficos que exportamos, conjuntos de datos que están tratados y limpios...y así.

### Code efficiency / Code syntax (conventions)

En cuanto a eficiencia del código:
<img width="1021" alt="Captura de pantalla 2021-02-08 a las 22 36 45" src="https://user-images.githubusercontent.com/57899051/107284445-2418b080-6a5e-11eb-9174-f62979f460c6.png">
Te cuento, como idea, para que más adelante le eches un ratito.
Todo este código que se repite, se puede hacer con un bucle, iterando sobre los strings que es lo único que cambias. Te haces una lista con todas esas palabras (las que cambias, el resto del código es igual) y realizas lo mismo para cada elemento de la lista o iterable. ¿qué te parece? Échale un ojo con calma y me dices.

Todas [estas](https://github.com/AnadeLuna/Proyecto_WebSraping/blob/main/src/funtions_scraping.ipynb) funciones que están ¡¡súper bien!!. El siguiente paso es meterlas en un archivo.py y llamarlas desde el jupyter sin tener que definirlas varias veces en diferentes sitios... ¡¡ponte con ello!! y si tienes cualquier duda... ¡¡me dices!! 🚀 

Todo este codiguito se puede refactorizar también y hacer en alguna función... habría que pensar como, hay que meterse un poquitito en el fango, pero seguro que te ahorras líneas de código y practicas. 
<img width="913" alt="Captura de pantalla 2021-02-08 a las 22 47 45" src="https://user-images.githubusercontent.com/57899051/107285578-ac4b8580-6a5f-11eb-9cc0-644f05131021.png">

Los gráficos están bien los que has hecho, para la próxima vez intenta probar otros gráficos diferentes y así poder contar tu historia desde diferentes puntos de vista...histográmas, gráficos de barras, scatter plots ¿valep?


### Improvements
Bueno, te dejo un resumen de todo lo que te he comentado. Partiendo de la base de que has hecho mucho trabajo y se nota, y has hecho un buen trabajo. Valoro mucho tu actitud y todo lo que te esfuerzas. Te digo también que si quieres ver cualquier cosa en concreto me digas ¿vale? podemos revisar lo que necesites.
- Los enlacitos del readme.
- Atomización del código en funciones.
- El ejecutable .py que hace cosas (en un hilo de ejecución) esto es lo más complicado, si necesitas verlo me dices.
- Pasar las funciones a un .py y llamarlas desde el jupyter.

¡¡Y eso es todo!! Espero haberte aportado cosas que te sirvan para mejorar cuando acabes el bootcamp y puedas echarle un ojo a estas correcciones si te apetece retocar estos proyectos.
¡¡Buen trabajo Ana!! ¡¡sigue dándole duro, que si no, te formateo el Mac!! 😄 

![unnamed2](https://user-images.githubusercontent.com/57899051/107285959-38f64380-6a60-11eb-941d-ca40dd0e4210.png)
