### ISSUE TITLE
[W3-pipelines-project] Xabier Arrieta

### ISSUE THREAD

**Issue by XabierArrieta** [Ironhack-Data-Madrid-Enero-2021/W3-pipelines-project#5]
https://github.com/XabierArrieta/Pipelines-Project-London-Transport

**Comment by breogann** [comment]
Hola Xabiiii! 🙋🏻‍♂️

Te comento: somos muy pesados, pero tener los proyectos bien hechos es muy importante, así que te voy a dar todo el feedback que pueda. 

El proyecto tenía dos objetivos: **enriquecer** datos & hacer un **pipeline**. 

- Para el primero: utilizar una API o web scrapping para relacionar los datos, como has hecho.
- Para el segundo: que  haya un pipeline quiere decir que el resultado de una función fuera la entrada de otra. Es decir, que ejecutando una acción, los datos se procesen de varias formas para devolver un output diferente al inicial. Aquí puedes hacer un ejecutable donde el resultado de la primera función (la descarga del dataset) sea la entrada de la(s) segunda(s) funcion(es) de limpieza. El flujo de ejecución sería:

    ruta  > df_descargado > df_limpio 

    En tu proyecto, has copiado y pegado las funciones, pero no están del todo bien. La idea es 100% esa. Peero tienes algunas funciones donde el return está a la misma altura que el def. La idea también de que fuera ejecutable es que una vez definidas las funciones, las llames. Si no se llaman, ese archivo sólo contiene código (que genial) pero no cumple la condición de ejecutable. 

- Respecto a la **organizacin del repositorio 📚**
    - El .gitignore:
        - Perfect. No se te ha colado ningún archivo temporal/oculto y también el el csv!
        - Lo único que te diría respecto a la organización es preferencia personal, porque tal y como está, está perfecta. Puedes agrupar los notebooks en una misma carpeta, pero si no, numéralos según el orden lógico que tengan: 1-cleaning, 2-scrapping, etc. Así se lo pones mucho más fácil a quien quiera seguir el hilo del proyecto (alguien: recruiters, aunque en general cualquiera que quiera leerlo).
- El **[README.md](http://readme.md) ✍🏻**:  Súper bien explicado el readme. Conciso pero con los puntos que necesitas.
    - Súper bien el uso de markdown para los títulos y para los enlaces, tanto los externos como los internos.
- El ejecutable ⚡️: has puesto el códido en el cleaning.py, peero no estás exportando el dataframe. No es cuestión de copiar y pegar el código (que un poco sí), pero tienes que meterlo en funciones y luego llamarlas, para que lo que se ejecute sean funciones y no tanto líneas de código. Asegúrate de al final exportarlo también.
- Respecto al código 👩‍💻:
    - Lo que te comentaba, en el archivo de funciones tienes algunas que están definidas con código al mismo nivel que el def. Eso te dará error.
    - Pero veo que las has importado bien en el jupyter y que las utilizas para la limpieza 🙌 Súuper top Xabi!!
    - En las funciones, veo que has puesto los comentarios, pero intenta también poner los docstrings:

        ```python
        def hacercosas():
        '''Esto hace cosas. 
        Recibe: algo. 
        Devuelve: otra cosa'''
        	return otra cosa
        ```

        haz la documentación como te gustaría encontrártela. 

    - Limita el print del jupyter pls 🙏
    - En esta función:

        ```python
        elif nombre == 'VicÃ¡lvaro':
                return 'nombre'

        #no hace nada, no? 👀
        ```

    - Súper bien el uso de la comprehension list:

        ```python
        att = [(i.text.strip()) for i in mad_att]
        ```

    - Súper top el geocoder 👏👏 y la de haversin que te comenté para calcular distancias. Esta la usarás mucho este finde, y eso que ya llevas adelantado.

Está genial el proyecto Xabi! Has limpiado dataframes, has hecho web scrapping , has sacado coordenadas y has enriquecido un montón el dataset👏 Puedes mejorarlo, los puntos clave que te faltan son:

1. Asegurarte de que el archivo de funciones está bien (indentaciones y demás)
2. Puedes separar los archivos: uno de limpieza y otro de scrapping, si quieres
3. Que puedas hacer el ejecutable: que no es más que llamar a las funciones que ya tienes hechas 🙂

Sigue así, que vas a sacar proyectazos!! 💪🚀
