### ISSUE TITLE
[W3-pipelines-project] Mario García Bruzón

### ISSUE THREAD

**Issue by MarioGar25** [Ironhack-Data-Madrid-Enero-2021/W3-pipelines-project#6]
My repo : https://github.com/MarioGar25/Pipelines-Project

**Comment by olmocorell** [comment]
¡¡Hola Hola Marioooooooooo 🚀 💪🏻 !! 
Perdona por haber tardado tanto en venir por aquí, te cuento cositas del proyecto.



### Readme
Woooooooooooooooooo ¡¡qué pasada!! Enhorabuena, está genial. Está súper chulo y has seguido todos los consejos que damos. ¡¡Así se hace!!
Solo te digo, por ponerme un poco tiquismiquis (que ya sabes que soy un poquito turras) que aquí:
<img width="529" alt="Captura de pantalla 2021-02-08 a las 22 53 30" src="https://user-images.githubusercontent.com/57899051/107286154-79ee5800-6a60-11eb-9062-edbddc14d56e.png">
Directamente puedes ponerlo en plan:

- [Pandas](https://pandas.pydata.org/) Manejo de datos
- [Loquesea](https://www.google.es/maps/preview) Descripción si quieres

Y así lo pones todo junto directamente y queda guay, yo creo.

### Code/Repository structure
La estructura del repo está perfecta ¡¡Nada que decir!!


### Code efficiency / Code syntax (conventions)
En [este](https://github.com/MarioGar25/Pipelines-Project/blob/main/src/analisys.py) archivo... partiendo de la base de que me ha parecido un espectáculo jajajaja y que me ha encantado tu creatividad...
Mi recomendación:
Esto realmente es un hilo de ejecución, esa función hace ¡¡MIL MILLONES DE COSAS!!
y NO ESTÁ mal que hagamos funciones largas, pero en este caso sí que haría diferentes funciones que hagan cosas y las iría llamando en un hilo de ejecución.

Imagínate que tienes que documentar lo que hace esa función jejeje

Por aquí:
<img width="825" alt="Captura de pantalla 2021-02-08 a las 22 59 16" src="https://user-images.githubusercontent.com/57899051/107286743-4829c100-6a61-11eb-8c2a-d69ba7a381f5.png">
Por una parte está genial que documentemos las funciones, esto es una buena práctica.
Por otra... intentamos hacer funciones generalistas, es decir, que si tú pones como parámetro un dataframe, puedes llamar a la función pasándole como parámetro un dataframe y así no hace falta que pongas que tienes que ejecutar la primera función.
De todos modos, esto también es un hilo de ejecución. Tú puedes definir las dos funciones y luego llamarlas y en vez de "return el dataframe" la función puede hacer un export de un csv. Es decir, las funciones no siempre tienen por qué devolver algo, pueden exportar cosas también. Y este podía ser el ejemplo de pipeline que nos explicaba Fer, que al ejecutar un archivo entran cosas y salen cosas. Realmente al ejecutar ese archivo directamente te bajabas el dataframe y lo limpias. Y está perfecto. Solo tienes que cambiar un par de líneas de código y añadir las llamadas a las funciones.

Te voy a dar caña por aquí porque tienes buen nivel y creo que puedes hacerlo:
<img width="646" alt="Captura de pantalla 2021-02-08 a las 23 02 15" src="https://user-images.githubusercontent.com/57899051/107287055-b3739300-6a61-11eb-813a-1b0d9f1a4d8b.png">
Esto lo puedes refactorizar súper fácil con un diccionario...iteras sobre él y le dices que si el elemento == key te devuelva el value ... 
Y por aquí igual:
<img width="484" alt="Captura de pantalla 2021-02-08 a las 23 03 33" src="https://user-images.githubusercontent.com/57899051/107287185-e158d780-6a61-11eb-8f44-c89f7b957e30.png">

Casi siempre que tenemos funciones con muchos elif podemos refactorizarlas haciendo un diccionario. Igual en este caso la función es tan cortita que no tiene mucho sentido, pero en la otra yo creo que sí, que con un diccionario te queda mejor. Échale un ojo.

El archivo de análisis... está realmente épico, la verdad, es increíble. Pf, no tengo palabras. Enhorabuena Mario, muy grande.


Te diría que esto del final lo "afea" y que igual puedes hacer un bucle que te salve todas las figuras del tirón o poner el savefig después de cada figura y no ponerlos todos juntos al final, es como un montón de código que se repite y que, realmente tiene sentido, pero no sé, como que me afea el jupyter.
<img width="722" alt="Captura de pantalla 2021-02-08 a las 23 05 15" src="https://user-images.githubusercontent.com/57899051/107287348-1e24ce80-6a62-11eb-81b8-a5f9c898d5e6.png">
Dale una vuelta y me dices.


### Improvements
A ver, te dejo poquito por aquí, la caña que te he podido dar, pero realmente tienes un nivel muy bueno, trabajas mucho, tienes una actitud genial y la verdad es que da gusto tenerte como alumno. Me ha encantado el jupyter de visualización, de verdad, me ha parecido una maravilla, hablando mal y bien, una fckn fantasía.

- Los enlacitos del readme que te he comentado
- Atomización de funciones gigantes que hacen mil cosas
- El ejecutable .py con las llamadas as las funciones
- Refactorizar las funciones que tienen muchos elif o código repetido

Y todo esto es por ponerme tiquismiquis y por aportarte cosas en tu aprendizaje, pero ante todo... ¡¡muy buen trabajo!!
Sigue así Mario, y te pasas Ironhack en nivel pro.
¡¡Enhorabuena!!

![unnamed2](https://user-images.githubusercontent.com/57899051/107287613-7c51b180-6a62-11eb-92ec-c14b365d3794.png)
