### ISSUE TITLE
[w3-pipelines-project] carlota portillo

### ISSUE THREAD

**Issue by xarlomi** [Ironhack-Data-Madrid-Enero-2021/W3-pipelines-project#7]
https://github.com/xarlomi/Pipelines-Project-Music-Genre.git

**Comment by breogann** [comment]
Hola Carlota! 🙋🏻‍♂️

Te comento:

El proyecto tenía dos objetivos: **enriquecer** datos & hacer un **pipeline.**

- Para el enriquecimiento: Has utilizado un dataset y has scrappeado ✅
- Para el pipeline: no tienes ningún ejecutable ❌
- Respecto a la **organización del repositorio 📚**
    - El .**gitignore**: no se te ha colado ningún archivo temporal/oculto.
    - Para el resto: sólo tienes tres jupyters. No tienes una carpeta de data (o dos carpetas, una de input y otra de output), no tienes una carpeta src donde almacenar código y tampoco archivos.py.
    - Las funciones que hayas utilizado en los jupyter luego tendrían que quedar en src/limpieza.py o src/scrapping.py
    - Mejor si los ordenas por título:
        - 1-Cleaning_Data.ipynb
        - 2-web_scrapping_genre.ipynb
        - 3-genre_danceability_visualization.ipynb
- El **[README.md](http://readme.md) ✍🏻**: está genial la introducción! Pero te faltaría más miga: las técnicas que has utilizado, la estructura de los datos, librerías, etc.
- El **ejecutable ⚡️**: una vez tengas el código en archivos.py, es cuestión de llamar a las funciones de limpieza, asegurarte del input que reciben y de ejecutar al archivo.
- Respecto al **código** 👩‍💻:
    - Tienes súper buen manejo de pandas! 👏
    - Para el jupyter de scrapping, limita el output para evitar el scroll infinito pls.
    - Sí que has utilizado dos métodos: el csv que ya tenías + el web scrapping. Pero como le dije a Jeancha en la presentación son datos que están relacionados por temática, pero no están cruzados ni se representan de forma conjunta. Es decir has obtenido datos de dos fuentes distintas, pero si no puedes unirlos o bien en los datos o bien en la visualización no tiene sentido el enriquecerlos.
    - Para los docstrings, cuando tenga las funciones (tanto de limpieza como de visualización):

        ```python
        def hacer_cosas ():
        '''Esto hace cosas.
        Takes: cosas
        Returns: otras'''
        	return cosas
        ```

        déjalo comentado como te gustaría encontrártelo.

    - Para la parte de visualización, creo que quizá no son los gráficos más acertados; tanto los scatters cmo los violinplot. Es difícil extraer conclusiones de ahí.

Lo más importante:

- Necesitas un archivo de python con **funciones**
- Scrappea otros datos o utiliza los que ya tienes de tal forma que tengan sentido en la visualización
- Una vez tengas el archivo de python, **ejecútalo** para que te devuelva el dataset limpio!
- Tienes muy buen manejo de pandas 💪

Dale duro al siguiente Carlota, que cambiando unas pocas cosas puedes hacer un proyecto muy top!!!
