### ISSUE TITLE
[W3-pipelines-project] Marina D

### ISSUE THREAD

**Issue by Marina-Diez** [Ironhack-Data-Madrid-Enero-2021/W3-pipelines-project#8]
https://github.com/Marina-Diez/Kaggle-Api-Project-MarinaD

**Comment by olmocorell** [comment]
¡¡Hola Hola Marinaaaaaaaaaa 🚀 💪🏻 !! 
La última corrección que te hago... ¡¡qué pena!! 😢 

### Readme
¡¡Está perfecto!! Muchas gracias por haber seguido todos los consejos de las correcciones, es exactamente esto lo que se espera de un buen readme. ¡¡Enhorabuena!!

### Code/Repository structure
¡Esto también está perfecto! La estructura del repositorio y la organización de archivos están muy bien. No me ha costado nada seguir el hilo y encontrar cada cosa en su sitio. ¡¡ 🔝 💯  !!
¡Además has hecho el ejecutable! 🥇

### Code efficiency / Code syntax (conventions)
Te cuento una cosa sobre el ejecutable solo, y es que está **realmente bien**, porque además llamas a otras funciones que están en el archivo de clean_utils, lo cual está perfecto.
Lo único que te falta aquí, es que directamente te ha faltado exportar el csv dentro de ese mismo ejecutable en vez de printearlo al final. Y este es el concepto de pipeline, una tubería por la que pasan varias cosas seguidas, en este caso, la limpieza del dataset. 
Así que al final, en la última línea, en vez de:
<img width="242" alt="Captura de pantalla 2021-02-08 a las 10 30 56" src="https://user-images.githubusercontent.com/57899051/107201010-bdad7700-69f8-11eb-8f02-579096459316.png">
Pues un export.csv 😄 y ¡¡perfect!!

Aquí: 
<img width="750" alt="Captura de pantalla 2021-02-08 a las 12 48 54" src="https://user-images.githubusercontent.com/57899051/107215751-04f13300-6a0c-11eb-8f92-06e8a9e66aca.png">
Realmente el value_counts() es una función que solemos realizar en un jupyter, que nos suele dar información cuando estamos trabajando con el dataframe, para tener información, pero no nos hace falta en un archivo ejecutable de limpieza, porque no hace ninguna acción sobre el dataframe.

Enhorabuena por el web scraping, es de mucha utilidad y cómo lo has hecho me ha parecido muy  muy bien.

### Improvements
Tienes poco que mejorar en este proyecto, porque está muy bien. De verdad. 
Puedes intentar atomizar el código un poco más en funciones y hacerlo todo en ejecutables, realmente. 


En general has hecho, una vez más, un muy buen proyecto. Haces lo que se te pide de una forma eficiente, ordenada y meticulosa. Ese modus operandi te va a llevar muy lejos Marina.
Enhorabuena por tu trabajo, de verdad.

![unnamed2](https://user-images.githubusercontent.com/57899051/107216294-daec4080-6a0c-11eb-9505-ace266c9610d.png)
