### ISSUE TITLE
[W3-pipelines-project] - Alfredo Zavala

### ISSUE THREAD

**Issue by alfredozavala14** [Ironhack-Data-Madrid-Enero-2021/W3-pipelines-project#9]
https://github.com/alfredozavala14/Project-Data-Pipeline

**Comment by olmocorell** [comment]
¡¡Hola Hola Alfredo 🚀 💪🏻 !! 
¡¡Te cuento cositas del proyecto de pipelines!!

### Readme
Está súper bien, la verdad. Has seguido todos los consejos que hemos dado y has hecho un readme bastante bueno. Lo único que yo pondría los enlaces en la parte del stack de tecnologías, y si luego tienes enlaces extra, pues una parte de enlaces está perfect, pero que directamente pongas la tecnología con el enlace a la documentación.
<img width="594" alt="Captura de pantalla 2021-02-08 a las 15 33 49" src="https://user-images.githubusercontent.com/57899051/107233602-0e39ca00-6a23-11eb-84f7-0fdedc9dd798.png">
El resto genial

### Code/Repository structure
En cuanto a la estructura del repositorio en sí está muy bien.
Me ha faltado el archivo main.py o loquesea.py que directamente al ejecutarlo es capaz de recibir un archivo, llamar a varias funciones en un hilo de ejecución, y exporta un dataframe limpio ya.


### Code efficiency / Code syntax (conventions)
Vamos con la eficiencia del código:
[Aquí](https://github.com/alfredozavala14/Project-Data-Pipeline/blob/main/src/happiness_report_functions.py) te propongo que atomices un poco este código en funciones más concretas que hagan una sola cosa.
Me refiero a clean_data_set, que es una función que hace un montón de cosas.

Luego, en cuanto a eficiencia. 
Si vemos que repetimos código, todo esto se puede hacer con una función...y con un bucle. Es decir, puedes iterar sobre una lista de columnas de un dataframe y sacarte en bucle los histogramas...
<img width="830" alt="Captura de pantalla 2021-02-08 a las 15 47 50" src="https://user-images.githubusercontent.com/57899051/107235479-02e79e00-6a25-11eb-8824-b7237bf8120b.png">

Y aquí igual, mira en esta celda la cantidad de código que se repite realmente...
<img width="1117" alt="Captura de pantalla 2021-02-08 a las 15 48 45" src="https://user-images.githubusercontent.com/57899051/107235596-23175d00-6a25-11eb-8dc8-770200f67f47.png">


### Improvements
- Enlaces del readme, reorganizar
- Atomización del código en funciones más generalistas y de propósito único
- Código repetido == Funciones & bucles
- Archivo ejecutable con hilo de ejecución (pipeline)

Pero en general has hecho muy buen trabajo, el hecho de documentar las funciones es una buena práctica y el archivo de visualización está genial.
¡¡Enhorabuena Alfredo!! ¡¡sigue así!!


![unnamed2](https://user-images.githubusercontent.com/57899051/107235902-738eba80-6a25-11eb-904c-1c3ea59cff02.png)
